version: 3
vars:
  NEXT_TAG:
    sh: '{{.TASKFILE_DIR}}/get_next_tag.py'

tasks:
  generate:
    label: "Generate Appstream metadata and download it"
    cmds:
      - "ansible-playbook -i inventory/hosts.yml -K playbook.yml"

  commit:
    label: "Add, commit, and tag new appstream data"
    cmds:
      - "git add solus-1-failed.xml.gz solus-1-icons.tar.gz solus-1-ignore.xml.gz solus-1-screenshots.tar solus-1.xml.gz"
      - "git commit -m 'Refresh Appstream metainfo'"
      - "git tag {{.NEXT_TAG}}"

  push:
    label: "Push changes to getsolus/solus-appstream-data"
    cmds:
      - "git push"
      - "git push origin {{.NEXT_TAG}}"

  full-process:
    label: "Perform the entire appstream generation process"
    cmds:
      - task: generate
      - task: commit
      - task: push

  appstream-init:
    label: "Set up the local system to run this tooling"
    cmds:
      - "sudo eopkg install pyyaml ansible"
      - "ansible-galaxy collection install community.general"
